language: java
jdk:
  - oraclejdk8

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn clean deploy -Dgpg.passphrase=yourpassphrase --settings target/travis/settings.xml"

# whitelist
branches:
  only:
    - develop
    - master
