language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - gpg --version
  - gpg2 -- version

script:
  - mvn deploy -X -Prelease-sign-artifacts --settings settings.xml

